### PR TITLE
Remove typings

### PR DESCRIPTION
**Pull request by zerovox**
re #12

### CODE REVIEW

**Comment by zerovox** [comment]
I signed it

**Comment by zerovox** [comment]
I signed it

**Comment by jcgregorio** [comment]
Thanks!

**Comment by marwahaha** [comment]
Did you plan to merge this?

**Comment by jcgregorio** [comment]
Thanks for the heads up, I thought I had merged it!

**Comment by marwahaha** [comment]
Thanks! I'd love if we do a release to 0.1.4 so I can consume this package!

**Comment by jcgregorio** [comment]
Done, let me know if it works!

**Pull request merged**
