### PR TITLE
fixes parsing of angles in Path2d

### PR DESCRIPTION
**Pull request by Botz**
If there is a path with an Arc the path couldn't be parsed.

I also fixed a bug with multiple m/M commands in an SVG path

### CODE REVIEW

**Comment by Botz** [comment]
I signed it!

**Comment by Botz** [comment]
I signed it!

**Comment by jcgregorio** [comment]
Thanks for the PR! Please make the changes to canvasv5.js and then generate canvas.js from that file by running:

    make canvas.js

Also, can you add some tests that confirm the fix actually works?

   Thanks,
   -joe

**Comment by Botz** [comment]
@jcgregorio Any news to this?

**Comment by hn3000** [comment]
Any chance this might get published soon?

**Comment by Link2Twenty** [comment]
@jcgregorio are you still the person to go to for getting things merged?

**Pull request closed without merging**
